memory_limit = 512M
max_execution_time = 300
max_input_vars = 1500
upload_max_filesize = 32M
post_max_size = 32M
opcache.enable = 1
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
